config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :students
	#get '/home' => 'pages#index'
	root to: 'pages#index'
end

app/models/request_room.rb
class RequestRoom < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
	
end

app/controllers/request_rooms_controller.rb
class RequestRoomsController < ApplicationController
  before_action :set_request_room, only: [:show, :edit, :update, :destroy]

  # GET /request_rooms
  # GET /request_rooms.json
  def index
    @request_rooms = RequestRoom.all
  end

  # GET /request_rooms/1
  # GET /request_rooms/1.json
  def show
  end

  # GET /request_rooms/new
  def new
    @request_room = RequestRoom.new
  end

  # GET /request_rooms/1/edit
  def edit
  end

  # POST /request_rooms
  # POST /request_rooms.json
  def create
    @request_room = RequestRoom.new(request_room_params)

    respond_to do |format|
      if @request_room.save
        format.html { redirect_to @request_room, notice: 'Request room was successfully created.' }
        format.json { render :show, status: :created, location: @request_room }
      else
        format.html { render :new }
        format.json { render json: @request_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_rooms/1
  # PATCH/PUT /request_rooms/1.json
  def update
    respond_to do |format|
      if @request_room.update(request_room_params)
        format.html { redirect_to @request_room, notice: 'Request room was successfully updated.' }
        format.json { render :show, status: :ok, location: @request_room }
      else
        format.html { render :edit }
        format.json { render json: @request_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_rooms/1
  # DELETE /request_rooms/1.json
  def destroy
    @request_room.destroy
    respond_to do |format|
      format.html { redirect_to request_rooms_url, notice: 'Request room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_room
      @request_room = RequestRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_room_params
      params.require(:request_room).permit(:house_adress, :other_house_details, :house_image, :room_availability, :number_people_in_Room, :room_cost, :other_room_details, :room_image)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:house_adress, :other_house_details, :room_availability, :number_people_in_Room, :room_cost, :other_room_details, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
		content_for(:header) { text.to_s }
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/request_rooms_helper.rb
module RequestRoomsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> navigation</title>
  </head>
  <body>
      <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <%= link_to 'SWANZA', root_path, class: 'navbar-brand' %>
          </div>
          <div id="navbar">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Home', root_path %></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
              <% if student_signed_in? %>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <%= current_student.first_name%>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Profile', edit_student_registration_path %></li>
                    <li><%= link_to 'Log out', destroy_student_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to 'Log In', new_student_session_path %></li>
                <li><%= link_to 'Sign Up', new_student_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
          </nav>

          <div class="container">
            <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>">
              <%= value %>
            </div>
          <% end %>
          </div>

          <%= yield :top_content %>

          <div class="container">
              <h1><%= yield :header %></h1>
            <%= yield %>
          </div>

  </body>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swanza</title>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>

  <body class="<%= controller.controller_name%>">

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'CAPEROOMS', root_path, class: 'navbar-brand' %>
      </div>



      <div class="collapse navbar-collapse" id="myNavbar">

        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><a href="#"><b>About Us</b></a></li>
          <li><a href="#"><b>Rooms&Rates</b></a></li>
          <li><a href="#"><b>Activities</b></a></li>
          <li><a href="#"><b>Contact Us</b></a></li>
        </ul>

        <ul class="nav navbar-nav pull-right">
          <% if student_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_student.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', edit_student_registration_path %></li>
                <li><%= link_to 'Log out', destroy_student_session_path, method: :delete %></li>
              </ul>
            </li>

          <% else %>
            <li>
              <%= link_to 'Log In', new_student_session_path %>
            </li>
            <li><%= link_to 'Sign Up', new_student_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
  <div class="container">
    <h1><%= yield :header %></h1>
    <%= yield %>
  </div>
</body>

</html>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>
<!--
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg">
    <h1>Swanza</h1>
  </div>
</div>
-->
<p>
<%= link_to 'Register', new_student_registration_path, class: 'btn btn-primary btn-lg' %>
</p>

app/views/request_rooms/_form.html.erb
<%= form_with(model: request_room, local: true) do |form| %>
  <% if request_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_room.errors.count, "error") %> prohibited this request_room from being saved:</h2>

      <ul>
      <% request_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :house_adress %>
    <%= form.text_area :house_adress %>
  </div>

  <div class="field">
    <%= form.label :other_house_details %>
    <%= form.text_area :other_house_details %>
  </div>

  <div class="field">
    <%= form.label :house_image %>
    <%= form.text_field :house_image %>
  </div>

  <div class="field">
    <%= form.label :room_availability %>
    <%= form.text_field :room_availability %>
  </div>

  <div class="field">
    <%= form.label :number_people_in_Room %>
    <%= form.number_field :number_people_in_Room %>
  </div>

  <div class="field">
    <%= form.label :room_cost %>
    <%= form.text_field :room_cost %>
  </div>

  <div class="field">
    <%= form.label :other_room_details %>
    <%= form.text_area :other_room_details %>
  </div>

  <div class="field">
    <%= form.label :room_image %>
    <%= form.text_field :room_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/request_rooms/edit.html.erb
<h1>Editing Request Room</h1>

<%= render 'form', request_room: @request_room %>

<%= link_to 'Show', @request_room %> |
<%= link_to 'Back', request_rooms_path %>

app/views/request_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Request Rooms</h1>

<table>
  <thead>
    <tr>
      <th>House adress</th>
      <th>Other house details</th>
      <th>House image</th>
      <th>Room availability</th>
      <th>Number people in room</th>
      <th>Room cost</th>
      <th>Other room details</th>
      <th>Room image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_rooms.each do |request_room| %>
      <tr>
        <td><%= request_room.house_adress %></td>
        <td><%= request_room.other_house_details %></td>
        <td><%= request_room.house_image %></td>
        <td><%= request_room.room_availability %></td>
        <td><%= request_room.number_people_in_Room %></td>
        <td><%= request_room.room_cost %></td>
        <td><%= request_room.other_room_details %></td>
        <td><%= request_room.room_image %></td>
        <td><%= link_to 'Show', request_room %></td>
        <td><%= link_to 'Edit', edit_request_room_path(request_room) %></td>
        <td><%= link_to 'Destroy', request_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request Room', new_request_room_path %>

app/views/request_rooms/new.html.erb
<h1>New Request Room</h1>

<%= render 'form', request_room: @request_room %>

<%= link_to 'Back', request_rooms_path %>

app/views/request_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>House adress:</strong>
  <%= @request_room.house_adress %>
</p>

<p>
  <strong>Other house details:</strong>
  <%= @request_room.other_house_details %>
</p>

<p>
  <strong>House image:</strong>
  <%= @request_room.house_image %>
</p>

<p>
  <strong>Room availability:</strong>
  <%= @request_room.room_availability %>
</p>

<p>
  <strong>Number people in room:</strong>
  <%= @request_room.number_people_in_Room %>
</p>

<p>
  <strong>Room cost:</strong>
  <%= @request_room.room_cost %>
</p>

<p>
  <strong>Other room details:</strong>
  <%= @request_room.other_room_details %>
</p>

<p>
  <strong>Room image:</strong>
  <%= @request_room.room_image %>
</p>

<%= link_to 'Edit', edit_request_room_path(@request_room) %> |
<%= link_to 'Back', request_rooms_path %>

app/views/rooms/_form.html.erb
<%= form_with model: @room, local: true, html: { multipart: true } do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
 <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :house_adress %>
    <%= form.text_area :house_adress %>
  </div>

  <div class="field">
    <%= form.label :other_house_details %>
    <%= form.text_area :other_house_details %>
  </div>

  <div class="field">
    <%= form.label :room_availability %>
    <%= form.text_field :room_availability %>
  </div>

  <div class="field">
    <%= form.label :number_people_in_Room %>
    <%= form.number_field :number_people_in_Room %>
  </div>

  <div class="field">
    <%= form.label :room_cost %>
    <%= form.number_field :room_cost %>
  </div>

  <div class="field">
    <%= form.label :other_room_details %>
    <%= form.text_area :other_room_details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>House adress</th>
      <th>Other house details</th>
      <th>Room availability</th>
      <th>Number people in room</th>
      <th>Room cost</th>
      <th>Other room details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.house_adress %></td>
        <td><%= room.other_house_details %></td>
        <td><%= room.room_availability %></td>
        <td><%= room.number_people_in_Room %></td>
        <td><%= room.room_cost %></td>
        <td><%= room.other_room_details %></td>
        <td><%= image_tag room.image.url (:thumb) %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>


<%= image_tag @room.image.url(:medium) %>

<p>
  <strong>House adress:</strong>
  <%= @room.house_adress %>
</p>

<p>
  <strong>Other house details:</strong>
  <%= @room.other_house_details %>
</p>

<p>
  <strong>Room availability:</strong>
  <%= @room.room_availability %>
</p>

<p>
  <strong>Number people in room:</strong>
  <%= @room.number_people_in_Room %>
</p>

<p>
  <strong>Room cost:</strong>
  <%= @room.room_cost %>
</p>

<p>
  <strong>Other room details:</strong>
  <%= @room.other_room_details %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>